### ISSUE TITLE
Cover image is missing in some articles

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/news#1009]
**Describe the bug**
In this article, the cover image is not displayed:
https://www.freecodecamp.org/news/asynchronous-javascript-explained/ (Note: The cover image is .gif file)

I also went through other articles and found a few articles with the same problem:
https://www.freecodecamp.org/news/learn-javascript-reactivity-build-signals-from-scratch/ (.svg)
https://www.freecodecamp.org/news/how-to-create-a-figma-miro-style-canvas-with-react-and-typescript/ (.gif)

**To Reproduce**
1. Go to the URLs listed above
2. Check the cover image

**Expected behavior**
The cover image is displayed.

**Screenshots**
![cover_image_missing_1](https://github.com/user-attachments/assets/96ba31e6-d150-4490-8817-59837fc31192)
![cover_image_missing_2](https://github.com/user-attachments/assets/09ce4c10-e6ae-4049-99b9-69b7bb04756b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 129.0.6668.71 (Official Build) (64-bit)

**Additional context**
The cover images of these articles are in .gif or .svg format. Not sure if hashnode supports those formats for the cover image.

**Comment by ihechikara** [comment]
Thanks for pointing these out, @sidemt. I've reuploaded the images using the right format:

https://www.freecodecamp.org/news/asynchronous-javascript-explained/
![image](https://github.com/user-attachments/assets/83cd7ef5-db4d-4e0a-ae7c-b421b75ef2c7)

https://www.freecodecamp.org/news/learn-javascript-reactivity-build-signals-from-scratch/
![image](https://github.com/user-attachments/assets/b560480a-f4d7-40b0-99f1-672a1749b24c)

https://www.freecodecamp.org/news/how-to-create-a-figma-miro-style-canvas-with-react-and-typescript/
![image](https://github.com/user-attachments/assets/a881aac3-3f89-45bf-9d63-7a8c3a356f07)

**Comment by sidemt** [comment]
@ihechikara Thank you for handling this issue.

Just to be sure, does it mean Hashnode don't support those file formats for cover images?

As far as I can recall right now, there was another article that has a GIF cover image: 
https://www.freecodecamp.org/news/git-clone-branch-how-to-clone-a-specific-branch/
