### ISSUE TITLE
Update the copyright disclaimer on LICENSE and README.md to 2022

### ISSUE THREAD

**Issue by ghost** [freeCodeCamp/news#252]

**Comment by thisiskaransgit** [comment]
I'll do the work

**Comment by scissorsneedfoodtoo** [comment]
Thank you for opening this issue.

We've reviewed the pull requests related to this issue and decided not to merge them. See #272 for more details about why.

Please read our [Guidelines for Contributing](https://contribute.freecodecamp.org/) for more.

Thank you, and happy coding.
