### ISSUE TITLE
Create extensible serve configs

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/news#320]
The `serve` config we currently have is a lot of duplication that is not scalable. Instead, we need something that is extensible.

I intend to keep config more modular with this.

**Comment by raisedadead** [comment]
Where are these used?

```
"start:containers": "docker compose -f './docker-config/ghost/docker-compose.yml' up -d",
"stop:containers": "docker compose -f './docker-config/ghost/docker-compose.yml' down",
```

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, awesome, that sounds great. Would be good to reorganize things and to cut down on duplication as much as possible.

> Where are these used?
> 
> ```
> "start:containers": "docker compose -f './docker-config/ghost/docker-compose.yml' up -d",
> "stop:containers": "docker compose -f './docker-config/ghost/docker-compose.yml' down",
> ```

Those commands are used to start and stop the three Dockerized Ghost instances for the Cypress tests. Currently only the `start:containers` command is being using in `/.github/workflows/cypress.yml`. The `stop:containers` command is for convenience when I want to spin things down locally, usually after writing tests.

Please feel free to modify those script names or the commands themselves as you see fit.
