### ISSUE TITLE
Fail building a site if Ghost is set to private

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/news#383]

**Comment by raisedadead** [comment]
Key @scissorsneedfoodtoo, I think this issue is handled - that is even if Ghost is set to private the builds still work fine? Correct?

**Comment by scissorsneedfoodtoo** [comment]
Hey @raisedadead, yes, this is no longer an issue. We can do test builds for sites if we add files / strings similar to [this PR](https://github.com/freeCodeCamp/news/pull/432), and also [add a YAML file for trending text and links](https://github.com/freeCodeCamp/cdn/pull/154) to the CDN repo.
