### ISSUE TITLE
Extra Scroll padding for linked section

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/news#528]
**Describe the feature**
When you visit a linked section like this https://www.freecodecamp.org/news/developer-news-style-guide#headlines-the-only-part-of-your-tutorial-that-100-of-people-will-read, you will face a missing section of the heading.

![Screenshot_2022-12-28-18-04-35-27_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/88248797/209839683-79558396-dfed-4b13-9b59-99cdf7a1ad54.jpg)

-----

We can use `scroll-padding-top`  to set offset for this, here is the link for it

https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top

**Comment by ASANIYAN** [comment]
Hi Sboonny,
My name is Ayomide and I am fairly new to open-source contributions. I would love to try my hand at fixing this issue. 
Can you give me some guidance on how to get started and what steps I should take to contribute to this issue?
Thank you.

**Comment by Sboonny** [comment]
You can start by reading our contribution guide https://contribute.freecodecamp.org/

**Comment by ASANIYAN** [comment]
Thank you. 
I'm already doing that.
Can you assign to me?

**Comment by Sboonny** [comment]
Only issues with the https://github.com/freeCodeCamp/freeCodeCamp/labels/help%20wanted or https://github.com/freeCodeCamp/freeCodeCamp/labels/first%20timers%20only label is open for contribution. The first comprehensive PR created will be reviewed and merged. We typically do not assign issues to anyone other than long-time contributors.

If you would like to contribute, and have not read the contributors docs, please do so here: https://contribute.freecodecamp.org/#/

If you have any issues with contributing, be sure to join us on the [contributors channel](https://discord.com/channels/692816967895220344/715074489422970962), or on the [contributors sub-forum](https://forum.freecodecamp.org/c/contributors/3)

**Comment by den319** [comment]
hi, can I work on this issue?

**Comment by jcubic** [comment]
I fixed the issue in round:
* #1000
