### ISSUE TITLE
Remove `sanitize-html` dependency

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/news#570]
Updating `sanitize-html` to a newer version seems to break AMP pages.

Rather than updating this dependency, it would be better to remove `sanitize-html` entirely. We only use it for AMP pages and already do quite a bit of manual transformations for AMP HTML.

We would mainly just need to make sure that the AMP HTML that isn't run through `sanitize-html` is valid. Using a manual AMP checker on some pages should be enough to verify that.

Ref: https://github.com/freeCodeCamp/news/pull/562

**Comment by a2937** [comment]
Do I have permission to remove it?

**Comment by naomi-lgbt** [comment]
Closed in #656
