### ISSUE TITLE
Where can I find the original markdown file for this article?

### ISSUE THREAD

**Issue by xgqfrms** [freeCodeCamp/news#584]
# Where can I find the original markdown file for this article?

https://www.freecodecamp.org/news/how-to-learn-javascript-effectively/

**Comment by xgqfrms** [comment]
https://github.com/freeCodeCamp/news/tree/main/src/docs
https://github.com/freeCodeCamp/news/tree/main/src/posts

???

https://github.com/freeCodeCamp/news/blob/main/docker/ghost/docker-compose.yml

**Comment by sidemt** [comment]
Hi @xgqfrms! Are you working on our translation effort? If so, which language?

**Comment by sidemt** [comment]
The articles are not stored in markdown format. But if you are working on our translation effort, some language teams work with them in markdown format by converting the published articles into markdown. In that case, I recommend you to reach out to your language lead.
