### ISSUE TITLE
There should be a floating button for scrolling to top

### ISSUE THREAD

**Issue by 777Prabhjot** [freeCodeCamp/news#634]
**Describe the bug**
I think there should be a floating button that helps users to scroll to top after clicking on that button so that users don't have to scroll to top manually.

**Screenshots**
<img width="956" alt="Screenshot 2023-04-29 142639" src="https://user-images.githubusercontent.com/68184118/235294243-8f48c6b7-111e-4d37-8277-f82e308eb19c.png">

**Additional context**

**Comment by sainikhil-0521** [comment]
i can work on this. 
WIll u assign this for me!

**Comment by sricharanandra** [comment]
is this open to work?

**Comment by rajvinder-kaur** [comment]
hey i wish to contribute in this issue as a developer. kindly assign this issue to me

**Comment by AsmitaMishra24** [comment]
Can you please assign this issue to me? I'm excited to contribute!

**Comment by scissorsneedfoodtoo** [comment]
Closing this as not planned, for reasons mentioned here: https://github.com/freeCodeCamp/news/pull/999#issuecomment-2434428968
