### ISSUE TITLE
Set defaults in the config

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/news#64]
Need to audit set sane defaults in https://github.com/freeCodeCamp/news/tree/main/config once we go full JAMStack.

**Comment by raisedadead** [comment]
@scissorsneedfoodtoo can you confirm that there are reasonable defaults in place to prevent failed builds?

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, yes, I just did some tests and the defaults in the config file should be enough to prevent failed builds. Did some test builds and missing values (Algolia and AdSense keys, posts per page, etc.) won't result in failed builds.

Once the original  author / translator feature is decoupled from the actual build process, the only strict requirements we'll have are `LOCALE_FOR_UI` and the correct keys from Ghost for that locale.

I think we can close this for now, and adjust the defaults later if necessary.
