### ISSUE TITLE
Package json not updated

### ISSUE THREAD

**Issue by boni619** [freeCodeCamp/news#695]
These Package need to update   
  "@11ty/eleventy": "1.0.2",
  "@11ty/eleventy-upgrade-help": "1.0.1",
  "cypress": "10.11.0",
  "eslint-plugin-ghost": "2.18.1",
   "i18next": "21.10.0",
    "i18next-fs-backend": "1.2.0",
    "jest": "27.5.1",
    "jsdom": "19.0.0",
    "libxmljs": "0.19.10",
    "lint-staged": "12.5.0",
    "node-fetch": "2.6.12",
     "piscina": "3.2.0",
    "prettier": "2.8.8",

**Comment by npxpatel** [comment]
Is this issued assigned by someone? Would be happy to solve it.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for the heads up about this, @Boni619.

Most of our package updates are handled by Renovate, so I'll close this as unplanned.
