### ISSUE TITLE
Ensure RSS feeds work just as the current Ghost version

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/news#70]
Currently to view RSS feeds on the landing, author, and tag pages, you need to go to `.../rss.xml` directly, rather than `.../rss` like on Ghost.

We'll need a way to serve `rss.xml` files when readers visit `.../rss`, either on the NGINX level, or with Serve.

**Comment by scissorsneedfoodtoo** [comment]
The rewrite for the main RSS is working, but the ones for the [author](https://www.freecodecamp.dev/italian/news/author/alessia/rss.xml) and [tag](https://www.freecodecamp.dev/italian/news/tag/git/rss.xml) pages don't.

I suspect this is because Serve is using `/news` as a base path, and doesn't expect longer possible paths for this rewrite.

**Comment by raisedadead** [comment]
I have landed the linked PR & deployed it to staging. @scissorsneedfoodtoo can you confirm this works as intended and can be closed?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for taking care of this too, @raisedadead.

Just checked on the staging Italian News site and the rewrites for the RSS feeds work as expected:
* https://www.freecodecamp.dev/italian/news/rss
* https://www.freecodecamp.dev/italian/news/author/alessia/rss
* https://www.freecodecamp.dev/italian/news/tag/freecodecamp/rss

Took a quick look at the other languages and the rewrites for those RSS feeds appear to work as well.
