### ISSUE TITLE
Ensure post & page redirects work just as the current Ghost version

### ISSUE THREAD

**Issue by scissorsneedfoodtoo** [freeCodeCamp/news#71]
Ghost has been handling the redirects for us, which we've been tracking in the [Ghost Config repo](https://github.com/freeCodeCamp/ghost-config).

We'll need a way to handle these redirects, too, either at the NGINX level, or with Serve.

**Comment by raisedadead** [comment]
The infra for this I believe is ready now, the idea is we are going to build a container for each publication. The configs for each language will be available in [`docker-config`](https://github.com/freeCodeCamp/news/tree/main/docker-config)

Mind adding some and we can test it out in the next deployment?

To be clear, there will probably be a bit of duplication because we need a different `serve.json` file for each language, but we can revisit the strategy at some point if we need DRY configs.

**Comment by raisedadead** [comment]
I think some redirects like RSS etc, are working. But not everything is.

**Comment by raisedadead** [comment]
Not sure, why these do not work:

https://github.com/freeCodeCamp/news/blob/65985ddfc8c015545d7e618837d70fffa16b04c9/docker-config/italian/serve.json#L7-L10

-- 

About these:

https://github.com/freeCodeCamp/news/blob/65985ddfc8c015545d7e618837d70fffa16b04c9/docker-config/italian/serve.json#L19-L26

Is the idea to show users a localized version of the about, etc.?

**Comment by scissorsneedfoodtoo** [comment]
I'm not sure why those first ones don't work either. It may be better to use [routing segments](https://github.com/vercel/serve-handler#rewrites-array) that are mentioned in the docs. Maybe something like:

```
 { 
   "source": "/@:username", 
   "destination": "/author/:username" 
 }, 
```

For the other redirects, I just wanted to confirm that those were all working. We could point to localized versions if those exist, or to the English versions of the articles for ones that we don't localize.

From the test redirects in that PR, I believe sponsors is the only one that should point to the English version of the article: https://www.freecodecamp.org/news/sponsors/

**Comment by raisedadead** [comment]
I have landed the linked PR & deployed it to staging. @scissorsneedfoodtoo can you confirm this works as intended and can be closed?

**Comment by scissorsneedfoodtoo** [comment]
Awesome, thanks @raisedadead.

I did some testing previously and we should be able to handle all the current Ghost redirects with Serve. The only hangup might be if we need to do something fancy with regex, though I don't see that happening very often -- most of the current redirects are for the migrated articles, or to point to another article for some reason or another.

Just double checked and the Dothraki redirects work as expected. Once we do test Chinese and English builds I can do a more in-depth check.
