### ISSUE TITLE
footer column size mismatch between learn and news

### ISSUE THREAD

**Issue by ahmaxed** [freeCodeCamp/news#827]
The columns of the news footer seem to be tighter comparing to learn:

Learn:
<img width="1728" alt="Screenshot 2024-02-27 at 3 23 21 PM" src="https://github.com/freeCodeCamp/news/assets/4591597/f58f9704-4498-4fdf-9c8a-14d74f393e24">

News:
<img width="1728" alt="Screenshot 2024-02-27 at 3 23 13 PM" src="https://github.com/freeCodeCamp/news/assets/4591597/7c1ee359-3aa4-45b0-9e97-07f9a447ac3f">

**Comment by raisedadead** [comment]
You are correct, and I am quite sure this is a `wontfix` because of the CSS libs on both projects. Trying to fix one breaks the other and so on. 

We can get "close enough" right now, and when we have the UI components, then it should be a standard baseline that resolves issues like these.
