### ISSUE TITLE
How to Help Translate freeCodeCamp into Your Native Language

### ISSUE THREAD

**Issue by anastasiiauk** [freeCodeCamp/news#846]
https://www.freecodecamp.org/news/help-translate-freecodecamp-language/

**Comment by anastasiiauk** [comment]
[Translated article](https://www.freecodecamp.org/ukrainian/news/yak-dopomohty-z-perekladom-freecodecamp-na-ridnu-movu/)

**Comment by sidemt** [comment]
Hi @anastasiiauk looks like you created the translation task issue in a wrong repo. It should be under /news-translation-tasks

**Comment by anastasiiauk** [comment]
Hi Yoko,
Thanks for pointing that out! It was the first translation task issue that
I’ve created, just getting to know the flow of everything. Soon after I
realized that something was wrong and deleted the issue.

Thanks again and sorry for the trouble. :)

**Comment by sidemt** [comment]
@anastasiiauk OK, thanks for confirming! No problem. It looks like you have removed the issue from the GitHub project board, but it was remaining open in the /news repository. I'm closing it now.
